# Generated by Django 5.1.3 on 2024-12-02 05:32

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactNo', models.CharField(blank=True, max_length=15)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('college_name', models.CharField(max_length=50)),
                ('highest_education', models.CharField(choices=[('HS', 'High School'), ('AA', 'Associate Degree'), ('BA', "Bachelor's Degree"), ('MA', "Master's Degree"), ('PHD', 'Doctorate'), ('OT', 'Other')], default='OT', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
