# Generated by Django 5.1.3 on 2024-12-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='user/profile_pics'),
        ),
    ]
