# Generated by Django 5.1.3 on 2024-12-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_skill_userprofile_bio_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='highest_education',
        ),
    ]
