# Generated by Django 5.1.3 on 2024-12-04 14:58

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_userprofile_college_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='endyear',
        ),
        migrations.RemoveField(
            model_name='education',
            name='highest_education',
        ),
        migrations.RemoveField(
            model_name='education',
            name='name',
        ),
        migrations.RemoveField(
            model_name='education',
            name='startyear',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userskill',
            name='user',
        ),
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('X', 'Class X'), ('XII', 'Class XII'), ('AA', 'Associate Degree'), ('BA', "Bachelor's Degree"), ('MA', "Master's Degree"), ('PHD', 'Doctorate'), ('OT', 'Other')], default='OT', max_length=255),
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='user.userprofile'),
        ),
        migrations.AddField(
            model_name='userskill',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contactNo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.DeleteModel(
            name='ProfilePageDetails',
        ),
    ]
